# Generated by Django 4.2.20 on 2025-04-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
