# Generated by Django 4.2.20 on 2025-11-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User'), ('DRIVER', 'Driver'), ('BUSINESS', 'Business')], default='USER', max_length=20),
        ),
    ]
