# Generated by Django 4.2.20 on 2025-11-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
