# Generated by Django 4.2.20 on 2025-12-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_paymenttransaction_transaction_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vehicle_make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehiclemake'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehiclemodel'),
        ),
    ]
