# Generated by Django 4.2.20 on 2025-12-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_vehicle_make_profile_vehicle_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='reviewTags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
